/**
 * Build the self-contained specops bundle committed at scripts/specops.mjs.
 * All dependencies (axi-sdk-js, @toon-format/toon) are inlined so the artifact
 * runs under plain `node` on a machine that only has the skill installed — no
 * npm install, no node_modules. This is what keeps the skill drop-in: `npx
 * skills add JarvusInnovations/specops` delivers a ready-to-run CLI.
 *
 *   bun scripts/build-cli.ts            # write the bundle
 *   bun scripts/build-cli.ts --check    # fail if the committed bundle is stale
 *
 * The CLI version is injected from `git describe`. Because committing the
 * bundle changes the git sha (and CI checkouts may lack tags), --check
 * normalizes the embedded version line out before comparing, so version drift
 * never fails the check while any real src/cli/ change still does.
 */
import * as esbuild from "esbuild";
import { readFileSync, chmodSync } from "node:fs";
import { execSync } from "node:child_process";

const OUTFILE = "scripts/specops.mjs";
const check = process.argv.includes("--check");

function gitVersion(): string {
  try {
    return execSync("git describe --tags --always", { encoding: "utf8" }).trim() || "dev";
  } catch {
    return "dev";
  }
}

/** Replace the embedded version literal so check ignores version drift. */
function normalizeVersion(source: string): string {
  return source.replace(/true \? "[^"]*" : "dev"/, 'true ? "__VERSION__" : "dev"');
}

const result = await esbuild.build({
  entryPoints: ["src/cli/bin.ts"],
  outfile: OUTFILE,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  legalComments: "none",
  define: { __SPECOPS_VERSION__: JSON.stringify(gitVersion()) },
  banner: {
    js: "#!/usr/bin/env node\n// GENERATED by scripts/build-cli.ts from src/cli/ — do not edit. Run `bun run build`.",
  },
  write: !check,
});

if (check) {
  const generated = result.outputFiles![0]!.text;
  const committed = readFileSync(OUTFILE, "utf8");
  if (normalizeVersion(generated) !== normalizeVersion(committed)) {
    console.error(`${OUTFILE} is out of date — run \`bun run build\` and commit the result`);
    process.exit(1);
  }
  console.log(`${OUTFILE} is up to date`);
} else {
  chmodSync(OUTFILE, 0o755);
  console.log(`Wrote ${OUTFILE}`);
}
