accountLevel = "user"
createdAt = "2020-03-31T14:49:17.000Z"
firstName = "Andrew"
fullName = "Andrew Eye"
id = "019e4021-204a-7368-b96b-534623da2f91"
lastName = "Eye"
legacyId = 4_694
slackSamlNameId = "a-eye-ceo-closedloop-ai"
slug = "a-eye-ceo-closedloop-ai"
updatedAt = "2020-03-31T14:49:33.000Z"
