accountLevel = "user"
createdAt = "2023-02-27T22:12:47.000Z"
firstName = "Anne"
fullName = "Anne Gemmell"
id = "019e4021-203d-75b5-a4f2-d331b3b79e2c"
lastName = "Gemmell"
legacyId = 12_192
slackSamlNameId = "a-gemm"
slug = "a-gemm"
updatedAt = "2023-02-27T22:17:13.000Z"
