accountLevel = "administrator"
createdAt = "2017-06-14T20:47:45.000Z"
firstName = "Maria"
fullName = "Maria Caruso"
id = "019e4021-2055-7398-8d19-48b0a5cc1f91"
lastName = "Caruso"
legacyId = 2_542
slackSamlNameId = "a-priori-rainbows"
slug = "a-priori-rainbows"
updatedAt = "2017-11-12T23:46:36.000Z"
