accountLevel = "user"
createdAt = "2016-02-24T15:04:00.000Z"
firstName = "Alisha"
fullName = "Alisha Ward"
id = "019e4021-205c-7319-b3ee-94d5f7c03ba8"
lastName = "Ward"
legacyId = 1_597
slackSamlNameId = "a-ward"
slug = "a-ward"
updatedAt = "2016-02-24T15:04:34.000Z"
