accountLevel = "user"
createdAt = "2025-07-16T09:29:01.000Z"
firstName = "a1environmental"
fullName = "a1environmental ca"
id = "019e4020-b161-7da7-8934-c3874edec810"
lastName = "ca"
legacyId = 28_866
slackSamlNameId = "a1environmentalca"
slug = "a1environmentalca"
updatedAt = "2025-07-16T10:49:01.000Z"
