accountLevel = "user"
createdAt = "2024-04-02T13:13:51.000Z"
firstName = "Amy"
fullName = "Amy Emerson"
id = "019e4020-e4e3-73de-967c-a51b7d376116"
lastName = "Emerson"
legacyId = 19_290
slackSamlNameId = "a2jhacker"
slug = "a2jhacker"
updatedAt = "2024-04-02T13:13:58.000Z"
