accountLevel = "user"
createdAt = "2019-07-08T23:52:22.000Z"
firstName = "Adam"
fullName = "Adam Peterson"
id = "019e4021-204f-7da9-8b97-ba523ad27073"
lastName = "Peterson"
legacyId = 3_632
slackSamlNameId = "a2peterson"
slug = "a2peterson"
updatedAt = "2019-07-08T23:52:26.000Z"
