accountLevel = "user"
bio = "IT professional to train in coding"
createdAt = "2014-10-11T22:18:23.000Z"
firstName = "Black"
fullName = "Black White"
id = "019e4021-294c-7ddf-9076-26bde7df594f"
lastName = "White"
legacyId = 660
slackSamlNameId = "a2zgiga"
slug = "a2zgiga"
updatedAt = "2014-10-11T22:18:23.000Z"
