accountLevel = "user"
createdAt = "2025-10-22T15:42:32.000Z"
firstName = "John"
fullName = "John Abraham"
id = "019e4020-b156-7778-b3d7-78e4d4195a5a"
lastName = "Abraham"
legacyId = 31_122
slackSamlNameId = "aaafurniture"
slug = "aaafurniture"
updatedAt = "2025-10-22T15:43:13.000Z"
