accountLevel = "user"
createdAt = "2026-03-28T13:33:34.000Z"
firstName = "Albert"
fullName = "Albert Adamson"
id = "019e4020-b139-7a57-9d3a-8025c02b7b61"
lastName = "Adamson"
legacyId = 35_776
slackSamlNameId = "aadamson26"
slug = "aadamson26"
updatedAt = "2026-03-28T13:51:02.000Z"
