accountLevel = "user"
bio = "My name is Aadya Nur, I have been serving Sagacia Jewelry under the capacity of Project Manager head for more than 2 years. Sagacia Jewelry is a global [Peridot Ring](https://www.sagaciajewelry.com/collections/dainty-peridot-rings) based in USA which deals in more than a hundred varieties of gemstones and a choice of metals and vermeil. We use only authentic and ethically sourced gemstones to create jewelry loved by jewelry resellers worldwide."
createdAt = "2024-09-19T05:07:27.000Z"
firstName = "Aadya"
fullName = "Aadya Nur"
id = "019e4020-e4d4-7de5-863c-95bc05cf09c6"
lastName = "Nur"
legacyId = 21_977
slackSamlNameId = "aadyanur"
slug = "aadyanur"
updatedAt = "2024-09-19T05:11:11.000Z"
