accountLevel = "user"
createdAt = "2021-05-14T20:01:27.000Z"
firstName = "AAfwkoz"
fullName = "AAfwkoz Drevers"
id = "019e4021-2046-7e2b-ace8-7b6019bcf197"
lastName = "Drevers"
legacyId = 6_340
slackSamlNameId = "aafwkoz"
slug = "aafwkoz"
updatedAt = "2021-05-14T20:01:27.000Z"
