accountLevel = "user"
createdAt = "2026-04-27T10:56:01.000Z"
firstName = "aah"
fullName = "aah trading"
id = "019e4020-b131-7fd4-b207-7314fadd86ac"
lastName = "trading"
legacyId = 36_691
slackSamlNameId = "aahtrading7865"
slug = "aahtrading7865"
updatedAt = "2026-04-27T10:56:29.000Z"
