accountLevel = "user"
bio = """
A​‍​‌‍​‍‌​‍​‌‍​‍‌ talented Plastic Surgeon in Jaipur provides state-of-the-art cosmetic as well as reconstructive surgeries to uplift the outward appearance and the self-esteem. By employing accurate methods, latest instruments, and individualized care, the best plastic surgeons in Jaipur make the patients look their most natural through facial, body and skin surgeries while maintaining their safety and ​‍​‌‍​‍‌​‍​‌‍​‍‌comfort.\r
Visit Our Website: https://www.aestheticsplasticsurgeon.com/plastic-surgeon-dr-aakansha-vashistha/"""
createdAt = "2025-11-07T10:00:34.000Z"
firstName = "Plastic Surgeon"
fullName = "Plastic Surgeon in JAIPUR"
id = "019e4020-b154-79fd-9a24-03d81dbd380d"
lastName = "in JAIPUR"
legacyId = 31_511
slackSamlNameId = "aakansha321"
slug = "aakansha321"
updatedAt = "2025-11-07T10:05:02.000Z"
