accountLevel = "user"
createdAt = "2017-09-05T22:24:16.000Z"
firstName = "Akash"
fullName = "Akash Patel"
id = "019e4021-2054-761a-9b22-c23424f5b2e7"
lastName = "Patel"
legacyId = 2_685
slackSamlNameId = "aakashpatel6600"
slug = "aakashpatel6600"
updatedAt = "2017-09-05T22:24:36.000Z"
