accountLevel = "user"
createdAt = "2024-04-09T10:49:44.000Z"
firstName = "AALIYAN"
fullName = "AALIYAN aaliyan"
id = "019e4020-e4e2-70bf-bb6b-41b704fdaaa5"
lastName = "aaliyan"
legacyId = 19_631
slackSamlNameId = "aaliyan"
slug = "aaliyan"
updatedAt = "2024-04-09T10:49:57.000Z"
