accountLevel = "user"
createdAt = "2024-06-12T09:37:26.000Z"
firstName = "Aamlye"
fullName = "Aamlye M M"
id = "019e4020-e4dc-7840-b8fc-48598e8ab79a"
lastName = "M M"
legacyId = 20_634
slackSamlNameId = "aamlye"
slug = "aamlye"
updatedAt = "2024-06-12T09:37:47.000Z"
