accountLevel = "user"
createdAt = "2024-11-04T06:18:17.000Z"
firstName = "leonal"
fullName = "leonal max"
id = "019e4020-e4ce-79ed-98c2-ed767cf08185"
lastName = "max"
legacyId = 23_381
slackSamlNameId = "aamliya"
slug = "aamliya"
updatedAt = "2024-11-04T06:19:33.000Z"
