accountLevel = "user"
createdAt = "2015-01-06T23:34:36.000Z"
firstName = "Ali"
fullName = "Ali Anari"
id = "019e4021-294b-7b2c-9460-495b1dfe8f95"
lastName = "Anari"
legacyId = 788
slackSamlNameId = "aanari"
slug = "aanari"
updatedAt = "2015-01-06T23:34:36.000Z"
