accountLevel = "user"
createdAt = "2024-04-17T10:47:29.000Z"
firstName = "Aanya"
fullName = "Aanya Patel"
id = "019e4020-e4e0-7739-82b6-cbdaf2779ff7"
lastName = "Patel"
legacyId = 19_964
slackSamlNameId = "aanya0"
slug = "aanya0"
updatedAt = "2024-04-17T10:47:35.000Z"
