accountLevel = "user"
createdAt = "2026-05-11T08:40:32.000Z"
firstName = "Aaradhya"
fullName = "Aaradhya varma"
id = "019e4020-b12d-7afa-bda4-93b17790f718"
lastName = "varma"
legacyId = 37_101
slackSamlNameId = "aaradhya"
slug = "aaradhya"
updatedAt = "2026-05-11T08:40:40.000Z"
