accountLevel = "staff"
createdAt = "2016-07-11T13:46:03.000Z"
firstName = "Aaron"
fullName = "Aaron Long"
id = "019e4021-205a-782b-95ce-07d27988db53"
lastName = "Long"
legacyId = 1_855
slackSamlNameId = "aaronlong"
slug = "aaronlong"
updatedAt = "2017-02-24T21:23:58.000Z"
