accountLevel = "user"
createdAt = "2016-02-03T21:31:09.000Z"
firstName = "Aaron"
fullName = "Aaron Wong"
id = "019e4021-2944-7b85-9cb0-37d08bcc2ef5"
lastName = "Wong"
legacyId = 1_545
slackSamlNameId = "aaronaaron"
slug = "aaronaaron"
updatedAt = "2019-10-01T17:31:48.000Z"
