accountLevel = "user"
createdAt = "2025-05-16T12:24:02.000Z"
firstName = "aarogyapath"
fullName = "aarogyapath care"
id = "019e4020-b169-745b-84cf-bd09fad3d9b1"
lastName = "care"
legacyId = 27_338
slackSamlNameId = "aarogyapathcare"
slug = "aarogyapathcare"
updatedAt = "2025-05-16T12:26:30.000Z"
