accountLevel = "user"
createdAt = "2016-03-15T22:56:17.000Z"
firstName = "Aaron"
fullName = "Aaron McKay"
id = "019e4021-205c-7319-b3ee-947a5a1d99c6"
lastName = "McKay"
legacyId = 1_633
slackSamlNameId = "aarodrago"
slug = "aarodrago"
updatedAt = "2021-11-08T17:27:53.000Z"
