accountLevel = "user"
bio = "I am a Full Stack Web Developer who specializes in custom web themes & plugins. I primarily work with Wordpress, yet have experience developing for all major content management systems."
createdAt = "2017-09-19T16:27:54.000Z"
firstName = "Aaron"
fullName = "Aaron Frey"
id = "019e4021-2054-761a-9b22-c20db6faeee0"
lastName = "Frey"
legacyId = 2_704
slackSamlNameId = "aaronfrey"
slug = "aaronfrey"
updatedAt = "2017-09-19T16:43:13.000Z"
