accountLevel = "user"
createdAt = "2022-06-09T15:40:36.000Z"
firstName = "Aaron"
fullName = "Aaron Warner"
id = "019e4021-2041-755f-99d0-85fb741c6d25"
lastName = "Warner"
legacyId = 9_684
slackSamlNameId = "aaron95"
slug = "aaron95"
updatedAt = "2022-06-09T15:47:38.000Z"
