accountLevel = "user"
createdAt = "2024-07-02T04:40:07.000Z"
firstName = "mat"
fullName = "mat Aaron"
id = "019e4020-e4d9-7290-9cad-888f54ba8730"
lastName = "Aaron"
legacyId = 20_998
slackSamlNameId = "aaronmarquardt"
slug = "aaronmarquardt"
updatedAt = "2024-07-02T04:40:25.000Z"
