accountLevel = "user"
bio = "Staff attorney at the Clean Air Council"
createdAt = "2014-05-21T01:04:01.000Z"
firstName = "Aaron"
fullName = "Aaron Jacobs-Smith"
id = "019e4021-294d-755f-9c8e-e4f9c662975c"
lastName = "Jacobs-Smith"
legacyId = 505
slackSamlNameId = "aaronrjs"
slug = "aaronrjs"
updatedAt = "2014-05-21T01:04:01.000Z"
