accountLevel = "user"
createdAt = "2020-03-18T19:04:48.000Z"
firstName = "Aaron"
fullName = "Aaron Cochran"
id = "019e4021-204b-75b6-8f5e-1aee509b0008"
lastName = "Cochran"
legacyId = 4_353
slackSamlNameId = "aaronc"
slug = "aaronc"
updatedAt = "2020-03-18T19:04:53.000Z"
