accountLevel = "user"
bio = """
https://istartsetup.com/\r
<a href="https://istartsetup.com/">ij.start.canon</a> is a platform for getting the canon printer driver.Install <a href="https://istartsetup.com/ij-start-cannon/">https //ij.start.canon</a> printer setup online or a disc to operate your Canon ij printer. .Visit <a href="https://istartsetup.com/ij-start-cannon/">http //ij.start.canon</a> to download printer drivers and start setting up your printer device. <a href="https://istartsetup.com/">ij.start canon</a> allows you to download, install, and configure on your PC, Mac and smartphones as well."""
createdAt = "2023-09-26T09:35:53.000Z"
firstName = "aaron"
fullName = "aaron wyatt"
id = "019e4021-2032-73bf-8bd5-94795b36d161"
lastName = "wyatt"
legacyId = 14_365
slackSamlNameId = "aaronwyatt183"
slug = "aaronwyatt183"
updatedAt = "2023-12-15T05:10:39.000Z"
