accountLevel = "user"
createdAt = "2020-03-20T21:51:08.000Z"
firstName = "Aaron"
fullName = "Aaron Watson"
id = "019e4021-204b-75b6-8f5e-1aa0870d84f1"
lastName = "Watson"
legacyId = 4_431
slackSamlNameId = "aaronw"
slug = "aaronw"
updatedAt = "2020-03-20T21:51:17.000Z"
