accountLevel = "user"
createdAt = "2018-02-17T13:58:57.000Z"
firstName = "Aaron"
fullName = "Aaron Moskowitz"
id = "019e4021-2053-7493-ac00-d3752f9f8652"
lastName = "Moskowitz"
legacyId = 2_938
slackSamlNameId = "aaron"
slug = "aaron"
updatedAt = "2018-12-04T15:07:33.000Z"
