accountLevel = "user"
createdAt = "2025-06-30T05:26:17.000Z"
firstName = "aarohi"
fullName = "aarohi yadav"
id = "019e4020-b163-797a-82a9-8cdf14e7d0b9"
lastName = "yadav"
legacyId = 28_371
slackSamlNameId = "aarohiyadav320"
slug = "aarohiyadav320"
updatedAt = "2025-06-30T05:28:37.000Z"
