accountLevel = "user"
createdAt = "2016-11-15T12:37:05.000Z"
firstName = "Aaron"
fullName = "Aaron Dennis"
id = "019e4021-2059-7223-8024-f5a698710d08"
lastName = "Dennis"
legacyId = 2_114
slackSamlNameId = "aaronpdennis"
slug = "aaronpdennis"
updatedAt = "2016-11-15T12:37:25.000Z"
