accountLevel = "user"
createdAt = "2017-10-21T16:12:09.000Z"
firstName = "Aaron"
fullName = "Aaron Bauman"
id = "019e4021-2054-761a-9b22-c1baec80ec6a"
lastName = "Bauman"
legacyId = 2_748
slackSamlNameId = "aaronbauman"
slug = "aaronbauman"
updatedAt = "2017-10-21T16:12:16.000Z"
