accountLevel = "user"
createdAt = "2015-10-20T15:03:11.000Z"
firstName = "Aaron"
fullName = "Aaron Peazzoni"
id = "019e4021-2946-79f7-86c3-1d958f5ea63b"
lastName = "Peazzoni"
legacyId = 1_370
slackSamlNameId = "aaron-peazzoni"
slug = "aaron-peazzoni"
updatedAt = "2016-01-21T16:27:10.000Z"
