accountLevel = "user"
bio = "Started by Mr. Yogesh Pradhan Director of [Aart Stroke](https://aartstroke.com/) Labels & Packs Pvt. Ltd. Flexible label printing services for papers and plastics all over India. Printing Self Adhesive labels, stickers and tubes both ABL & PBL Strong foothold in pharmaceutical sector. Aartstroke create exceptional quality labels that are widely acclaimed for the offered superior adhesion power, ease of use, all weather performance, long lasting tacking power, customizable range of design and materials, and cost competitiveness."
createdAt = "2025-05-08T09:53:56.000Z"
firstName = "Aart"
fullName = "Aart Stroke"
id = "019e4020-e4b4-7f96-9f80-e44fc4076af4"
lastName = "Stroke"
legacyId = 27_142
slackSamlNameId = "aartstroke"
slug = "aartstroke"
updatedAt = "2025-05-08T10:09:13.000Z"
