accountLevel = "user"
bio = "While working with ATSMantra, I play a key role in identifying and sharing updated openings for [jobs in Pune](https://atsmantra.com/job-openings/jobs-in-kolkata?location=Kolkata), helping candidates discover roles that truly align with their aspirations. With a pulse on industry trends and local hiring patterns, I assist professionals in making informed decisions, whether they're entering the job market or planning a strategic shift. My goal is to empower job seekers by providing insight, clarity, and direction in their journey toward meaningful employment in Kolkata."
createdAt = "2025-07-19T10:31:27.000Z"
firstName = "Aashi"
fullName = "Aashi Sharma"
id = "019e4020-b161-7da7-8934-c32c0474a670"
lastName = "Sharma"
legacyId = 28_946
slackSamlNameId = "aashi6742"
slug = "aashi6742"
updatedAt = "2025-07-19T10:39:04.000Z"
