accountLevel = "user"
bio = """
Thank you for sharing such a useful article, defiantly i will share to my friends and WhatsApp groups -\r
<a href="https://seoexpertindubai.in/"> best seo expert in dubai </a>\r
<a href="https://mohamedaasik.net/"> SEO freelancer in Dubai</a>\r
<a href="https://neejacs.com/business-setup-in-dubai-mainland/"> business setup in dubai</a>"""
createdAt = "2024-10-25T12:25:48.000Z"
firstName = "Mohamed"
fullName = "Mohamed Aasik"
id = "019e4020-e4ce-79ed-98c2-edea55596179"
lastName = "Aasik"
legacyId = 23_272
slackSamlNameId = "aasik90"
slug = "aasik90"
updatedAt = "2024-10-25T12:28:12.000Z"
