accountLevel = "user"
createdAt = "2026-04-24T10:18:17.000Z"
firstName = "Aathi"
fullName = "Aathi Vithyah"
id = "019e4020-b131-7fd4-b207-7346e84fc7a4"
lastName = "Vithyah"
legacyId = 36_641
slackSamlNameId = "aathivithyah"
slug = "aathivithyah"
updatedAt = "2026-04-24T10:18:22.000Z"
