accountLevel = "user"
bio = "Online purchase of kitchenware has gained more popularity in recent times. Most leading online platforms offer a wide range of products at exciting prices [Toasters](https://aawkitchens.com/products/appliances/food-preperations/toasters.html)  . This extensive selection of kitchenware covers many major brands and comes in varying sizes and styles."
createdAt = "2023-05-22T08:09:44.000Z"
firstName = "ebin"
fullName = "ebin mathew"
id = "019e4021-203a-7119-b743-3ce9391cd94b"
lastName = "mathew"
legacyId = 13_098
slackSamlNameId = "aaw12"
slug = "aaw12"
updatedAt = "2023-05-22T08:34:01.000Z"
