accountLevel = "user"
bio = "At Aayushka Living, our [retirement homes in ECR Chennai](https://aayushkaliving.com/) offer seniors a refreshing coastal lifestyle along the scenic East Coast Road. The peaceful surroundings, fresh sea breeze, and open spaces create a calming atmosphere perfect for relaxation. Our community blends nature with modern comfort, providing wellness programs, social activities, and attentive care. Residents enjoy independence while having access to all essential support. Whether they love gentle walks, meaningful conversations, or serene views, our ECR community ensures a rejuvenating and fulfilling retirement experience."
createdAt = "2025-11-28T06:19:58.000Z"
firstName = "Aayushka"
fullName = "Aayushka Living"
id = "019e4020-b153-7d25-84ba-cef0d1bde988"
lastName = "Living"
legacyId = 31_841
slackSamlNameId = "aayushka-living"
slug = "aayushka-living"
updatedAt = "2025-11-28T06:24:39.000Z"
