accountLevel = "user"
createdAt = "2026-05-05T09:38:33.000Z"
firstName = "Azhar"
fullName = "Azhar Khatri"
id = "019e4020-b12f-7fc6-a632-9b6b21406241"
lastName = "Khatri"
legacyId = 36_889
slackSamlNameId = "aaza"
slug = "aaza"
updatedAt = "2026-05-05T09:38:40.000Z"
