accountLevel = "user"
bio = "AB33 is a  [Trusted Malaysia Online Casino](https://www.ab33my6.com/), renowned for its reputation and offering a seamless and secure gaming experience. Experience the greatest slot games, live dealer tables, and massive prizes. With quick deposits and withdrawals, your money is always available. Asiabet33 is completely licensed and open 24 hours a day, seven days a week. You may play at any time. Don't miss out on the fun; register today!"
createdAt = "2025-07-17T04:33:44.000Z"
firstName = "Ab33"
fullName = "Ab33 Malaysia"
id = "019e4020-b161-7da7-8934-c3723794aabc"
lastName = "Malaysia"
legacyId = 28_882
slackSamlNameId = "ab33my"
slug = "ab33my"
updatedAt = "2025-07-17T04:35:23.000Z"
