/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'gitsheets-core.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./gitsheets-core.android-arm64.node')
          } else {
            nativeBinding = require('@gitsheets/core-napi-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'gitsheets-core.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./gitsheets-core.android-arm-eabi.node')
          } else {
            nativeBinding = require('@gitsheets/core-napi-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'gitsheets-core.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./gitsheets-core.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@gitsheets/core-napi-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'gitsheets-core.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./gitsheets-core.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@gitsheets/core-napi-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'gitsheets-core.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./gitsheets-core.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@gitsheets/core-napi-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'gitsheets-core.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./gitsheets-core.darwin-universal.node')
      } else {
        nativeBinding = require('@gitsheets/core-napi-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'gitsheets-core.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./gitsheets-core.darwin-x64.node')
          } else {
            nativeBinding = require('@gitsheets/core-napi-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'gitsheets-core.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./gitsheets-core.darwin-arm64.node')
          } else {
            nativeBinding = require('@gitsheets/core-napi-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'gitsheets-core.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./gitsheets-core.freebsd-x64.node')
      } else {
        nativeBinding = require('@gitsheets/core-napi-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'gitsheets-core.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./gitsheets-core.linux-x64-musl.node')
            } else {
              nativeBinding = require('@gitsheets/core-napi-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'gitsheets-core.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./gitsheets-core.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@gitsheets/core-napi-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'gitsheets-core.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./gitsheets-core.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@gitsheets/core-napi-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'gitsheets-core.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./gitsheets-core.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@gitsheets/core-napi-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'gitsheets-core.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./gitsheets-core.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@gitsheets/core-napi-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'gitsheets-core.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./gitsheets-core.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@gitsheets/core-napi-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'gitsheets-core.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./gitsheets-core.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@gitsheets/core-napi-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'gitsheets-core.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./gitsheets-core.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@gitsheets/core-napi-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'gitsheets-core.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./gitsheets-core.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@gitsheets/core-napi-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { roundtrip, parseRecords, serializeRecords, renderPathsBatch, validateBatch, canonicalContractHash, verifySheetContract, runComparator, collatorSort, CompiledDefinition, recordRead, recordWrite, recordDelete, recordList, writeBlob, substrateStats, substrateReset, recordQuery, recordQueryCandidates, templateFieldNames, recordIndexUnique, recordIndexMulti, createPatch, applyMergePatch, diffRecords, simulateCoreError, CoreTransaction, coreDiscoverSheets, coreCheckValidators, markdownSerialize, markdownNormalizeBody, markdownParse, markdownParseHeaderOnly, markdownExtractH1, markdownRewriteH1 } = nativeBinding

module.exports.roundtrip = roundtrip
module.exports.parseRecords = parseRecords
module.exports.serializeRecords = serializeRecords
module.exports.renderPathsBatch = renderPathsBatch
module.exports.validateBatch = validateBatch
module.exports.canonicalContractHash = canonicalContractHash
module.exports.verifySheetContract = verifySheetContract
module.exports.runComparator = runComparator
module.exports.collatorSort = collatorSort
module.exports.CompiledDefinition = CompiledDefinition
module.exports.recordRead = recordRead
module.exports.recordWrite = recordWrite
module.exports.recordDelete = recordDelete
module.exports.recordList = recordList
module.exports.writeBlob = writeBlob
module.exports.substrateStats = substrateStats
module.exports.substrateReset = substrateReset
module.exports.recordQuery = recordQuery
module.exports.recordQueryCandidates = recordQueryCandidates
module.exports.templateFieldNames = templateFieldNames
module.exports.recordIndexUnique = recordIndexUnique
module.exports.recordIndexMulti = recordIndexMulti
module.exports.createPatch = createPatch
module.exports.applyMergePatch = applyMergePatch
module.exports.diffRecords = diffRecords
module.exports.simulateCoreError = simulateCoreError
module.exports.CoreTransaction = CoreTransaction
module.exports.coreDiscoverSheets = coreDiscoverSheets
module.exports.coreCheckValidators = coreCheckValidators
module.exports.markdownSerialize = markdownSerialize
module.exports.markdownNormalizeBody = markdownNormalizeBody
module.exports.markdownParse = markdownParse
module.exports.markdownParseHeaderOnly = markdownParseHeaderOnly
module.exports.markdownExtractH1 = markdownExtractH1
module.exports.markdownRewriteH1 = markdownRewriteH1
