/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Round-trip a **batch** of records through the core, preserving full type
 * fidelity. The whole array crosses the FFI once. This is the foundation's
 * stand-in for the real batch engine entry points (`upsertMany`, `queryAll`,
 * …), which keep this same batch-first signature.
 */
export declare function roundtrip(records: Array<JsValue>): Array<JsValue>
/**
 * Throw the core error for a given stable `code`, surfaced as a **structured,
 * matchable** JS error (own `code`, `status`, `gitsheetsClass`, and any
 * `issues`/`conflictingPaths`). Boundary-test entry point: it exercises the
 * error-variant → typed-class mapping without standing up real engine paths.
 */
export declare function simulateCoreError(code: string): void
