/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Round-trip a **batch** of records through the core, preserving full type
 * fidelity. The whole array crosses the FFI once. This is the foundation's
 * stand-in for the real batch engine entry points (`upsertMany`, `queryAll`,
 * …), which keep this same batch-first signature.
 */
export declare function roundtrip(records: Array<JsValue>): Array<JsValue>
/**
 * Parse a **batch** of TOML documents into records, marshalled to JS with full
 * type fidelity. The whole array crosses the FFI once (batch-first). A
 * malformed document surfaces as a structured, typed core error (`config_invalid`).
 */
export declare function parseRecords(documents: Array<string>): Array<JsValue>
/**
 * Serialize a **batch** of records to their canonical TOML bytes in one call
 * (deep key sort + `toml`-crate default formatting; see `gitsheets_core::canonical`).
 * A value TOML can't represent surfaces as a structured, typed core error.
 */
export declare function serializeRecords(records: Array<JsValue>): Array<string>
/**
 * One JSON-Schema validation failure, marshalled to the `ValidationIssue`
 * shape the host surface uses (`source`/`schemaPath`/`code`, with snake fields
 * rendered camelCase by napi). Returned by [`validate_batch`].
 */
export interface JsValidationIssue {
  path: Array<string>
  message: string
  source: string
  schemaPath?: string
  code?: string
}
/**
 * Render a path template against a **batch** of records, returning one path per
 * record (no file extension; the caller appends `.toml`/`.md`). The template is
 * parsed and its expression components compiled into the embedded engine
 * **once**, then reused across the whole batch — the bulk path crosses the FFI
 * a single time. A render failure surfaces as a structured, typed
 * `PathTemplateError` (`path_render_failed` / `path_invalid_chars`). This is the
 * path-template half of the `node:vm` parity gate.
 */
export declare function renderPathsBatch(template: string, records: Array<JsValue>): Array<string>
/**
 * Validate a **batch** of records against a JSON Schema, returning the issues
 * for each record (an empty inner array ⇒ that record is valid). The schema is
 * compiled **once**, then reused across the batch. Unlike the host's throwing
 * `validateRecord`, this returns issues per record so a parity harness can diff
 * the full pass/fail + path/keyword picture against `ajv`. A schema that won't
 * compile surfaces as a structured, typed `ConfigError` (`config_invalid`).
 */
export declare function validateBatch(schema: JsValue, records: Array<JsValue>): Array<Array<JsValidationIssue>>
/**
 * Compile a raw-JS sort comparator (`rule`, the body of `(a, b) => { … }`) and
 * run it once against `a`/`b`, returning its numeric result. The direct
 * comparator-parity entry point: a harness asserts this equals the same rule
 * run through `node:vm` for identical inputs.
 */
export declare function runComparator(rule: string, a: JsValue, b: JsValue): number
/**
 * Read a batch of records by path. Each result is the record (a plain object
 * with full TOML type fidelity) or `null` when no blob lives at that path.
 */
export declare function recordRead(gitDir: string, treeRef: string, base: string, paths: Array<string>, extension?: string | undefined | null): Array<JsValue | undefined | null>
/**
 * The result of a `record_write`/`record_delete`: the new root tree hash plus
 * per-record output (`blobHashes` for writes, `existed` for deletes).
 */
export interface JsWriteOutcome {
  treeHash: string
  blobHashes: Array<string>
}
/** The result of a `record_delete`. */
export interface JsDeleteOutcome {
  treeHash: string
  existed: Array<boolean>
}
/**
 * Write a batch of records (canonical TOML) under `base`, starting from the
 * tree `baseRef`. `paths[i]` is written from `records[i]`. Returns the new root
 * tree hash + each written blob hash. The bytes are produced by the core's
 * bytes-authority, so two bindings writing the same record agree byte-for-byte.
 */
export declare function recordWrite(gitDir: string, baseRef: string, base: string, paths: Array<string>, records: Array<JsValue>, extension?: string | undefined | null): JsWriteOutcome
/**
 * Delete a batch of records by path under `base`, starting from `baseRef`.
 * `existed[i]` reports whether `paths[i]` was actually present.
 */
export declare function recordDelete(gitDir: string, baseRef: string, base: string, paths: Array<string>, extension?: string | undefined | null): JsDeleteOutcome
/**
 * One record from `record_list`: its path (relative to `base`, no extension)
 * and parsed value.
 */
export interface JsRecordEntry {
  path: string
  record: JsValue
}
/**
 * List every record under `base` in the tree `treeRef`, in sorted
 * (git-canonical) path order.
 */
export declare function recordList(gitDir: string, treeRef: string, base: string, extension?: string | undefined | null): Array<JsRecordEntry>
/**
 * Generate an RFC 6902 JSON Patch transforming `src` into `dst` — the core's
 * `createPatch`, matching the `rfc6902` package op-for-op. `null`/`undefined`
 * on either side is the JSON null `Sheet.diffFrom` passes for an added
 * (`src=null`) or deleted (`dst=null`) record.
 */
export declare function createPatch(src?: JsValue | undefined | null, dst?: JsValue | undefined | null): object
/**
 * Apply an RFC 7396 JSON Merge Patch to `target` (`null` ⇒ absent), returning
 * the merged record — the core's `mergePatch` behind `Sheet.patch`. A `null`
 * in the patch deletes that key; an object merges recursively; anything else
 * replaces wholesale. Returns `null` only when the patch deletes the record
 * outright.
 */
export declare function applyMergePatch(target: JsValue | undefined | null, patch: JsMergePatch): JsValue | null
/**
 * Diff records between two trees (`srcRef` → `dstRef`) under `base`, returning
 * one entry per change with status, src/dst blob hashes, the parsed src/dst
 * records, and the RFC 6902 patch — the full `Sheet.diffFrom({records,
 * patches})` payload, computed in the core. `srcRef` may be the empty-tree hash
 * for a from-scratch diff.
 */
export declare function diffRecords(gitDir: string, srcRef: string, dstRef: string, base: string, extension?: string | undefined | null): object
/**
 * Throw the core error for a given stable `code`, surfaced as a **structured,
 * matchable** JS error (own `code`, `status`, `gitsheetsClass`, and any
 * `issues`/`conflictingPaths`). Boundary-test entry point: it exercises the
 * error-variant → typed-class mapping without standing up real engine paths.
 */
export declare function simulateCoreError(code: string): void
/**
 * A compiled sheet definition: the embedded engine plus the definition's
 * path template (and optional raw-JS sort comparator), **compiled once** at
 * construction and reused across every method call. Holds a `!Send` boa
 * context, so it is constructed and used on its owning JS thread — the
 * thread-confinement the spec requires. Exists to demonstrate the
 * compile-once-per-open / reuse-across-operations contract from JS.
 */
export declare class CompiledDefinition {
  /**
   * Compile a definition once: parse the path template (compiling its
   * expression snippets into the engine) and, if given, compile a raw-JS sort
   * comparator. All snippet compilation happens here — never per operation.
   */
  constructor(pathTemplate: string, sortRule?: string | undefined | null)
  /** Render one record's path using the already-compiled template. */
  renderPath(record: JsValue): string
  /**
   * Run the compiled sort comparator on two values, returning its numeric
   * result. Errors if the definition was built without a sort rule.
   */
  compare(a: JsValue, b: JsValue): number
  /**
   * How many snippets were compiled into this definition's engine. Constant
   * across operations — proof that compilation happened once at construction,
   * not per `render_path` / `compare` call.
   */
  snippetCount(): number
}
