/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Round-trip a **batch** of records through the core, preserving full type
 * fidelity. The whole array crosses the FFI once. This is the foundation's
 * stand-in for the real batch engine entry points (`upsertMany`, `queryAll`,
 * …), which keep this same batch-first signature.
 */
export declare function roundtrip(records: Array<JsValue>): Array<JsValue>
/**
 * Parse a **batch** of TOML documents into records, marshalled to JS with full
 * type fidelity. The whole array crosses the FFI once (batch-first). A
 * malformed document surfaces as a structured, typed core error (`config_invalid`).
 */
export declare function parseRecords(documents: Array<string>): Array<JsValue>
/**
 * Serialize a **batch** of records to their canonical TOML bytes in one call
 * (deep key sort + `toml`-crate default formatting; see `gitsheets_core::canonical`).
 * A value TOML can't represent surfaces as a structured, typed core error.
 */
export declare function serializeRecords(records: Array<JsValue>): Array<string>
/**
 * One JSON-Schema validation failure, marshalled to the `ValidationIssue`
 * shape the host surface uses (`source`/`schemaPath`/`code`, with snake fields
 * rendered camelCase by napi). Returned by [`validate_batch`].
 */
export interface JsValidationIssue {
  path: Array<string>
  message: string
  source: string
  schemaPath?: string
  code?: string
}
/**
 * Render a path template against a **batch** of records, returning one path per
 * record (no file extension; the caller appends `.toml`/`.md`). The template is
 * parsed and its expression components compiled into the embedded engine
 * **once**, then reused across the whole batch — the bulk path crosses the FFI
 * a single time. A render failure surfaces as a structured, typed
 * `PathTemplateError` (`path_render_failed` / `path_invalid_chars`). This is the
 * path-template half of the `node:vm` parity gate.
 */
export declare function renderPathsBatch(template: string, records: Array<JsValue>): Array<string>
/**
 * Validate a **batch** of records against a JSON Schema, returning the issues
 * for each record (an empty inner array ⇒ that record is valid). The schema is
 * compiled **once**, then reused across the batch. Unlike the host's throwing
 * `validateRecord`, this returns issues per record so a parity harness can diff
 * the full pass/fail + path/keyword picture against `ajv`. A schema that won't
 * compile surfaces as a structured, typed `ConfigError` (`config_invalid`).
 */
export declare function validateBatch(schema: JsValue, records: Array<JsValue>): Array<Array<JsValidationIssue>>
/**
 * Compile a raw-JS sort comparator (`rule`, the body of `(a, b) => { … }`) and
 * run it once against `a`/`b`, returning its numeric result. The direct
 * comparator-parity entry point: a harness asserts this equals the same rule
 * run through `node:vm` for identical inputs.
 */
export declare function runComparator(rule: string, a: JsValue, b: JsValue): number
/**
 * Native locale array sort — the declarative `sort = true` path. Sorts the
 * strings with the ICU collator that matches V8's `localeCompare(b, undefined,
 * { sensitivity: 'base', ignorePunctuation: true, numeric: true })`. This is the
 * exact function `Sheet::normalize_record` applies for a `sort = true` field, and
 * it does **NOT** route through the boa engine (boa lacks `Intl`, so its
 * `localeCompare` falls back to code-unit order and diverges from `node:vm` on
 * non-ASCII / mixed-case input). Exposed so a `node --test` harness asserts
 * byte-exact parity against `node`'s `localeCompare` — see
 * `test/collator-parity.mjs`.
 */
export declare function collatorSort(strings: Array<string>): Array<string>
/**
 * Read a batch of records by path. Each result is the record (a plain object
 * with full TOML type fidelity) or `null` when no blob lives at that path.
 */
export declare function recordRead(gitDir: string, treeRef: string, base: string, paths: Array<string>, extension?: string | undefined | null): Array<JsValue | undefined | null>
/**
 * The result of a `record_write`/`record_delete`: the new root tree hash plus
 * per-record output (`blobHashes` for writes, `existed` for deletes).
 */
export interface JsWriteOutcome {
  treeHash: string
  blobHashes: Array<string>
}
/** The result of a `record_delete`. */
export interface JsDeleteOutcome {
  treeHash: string
  existed: Array<boolean>
}
/**
 * Write a batch of records (canonical TOML) under `base`, starting from the
 * tree `baseRef`. `paths[i]` is written from `records[i]`. Returns the new root
 * tree hash + each written blob hash. The bytes are produced by the core's
 * bytes-authority, so two bindings writing the same record agree byte-for-byte.
 */
export declare function recordWrite(gitDir: string, baseRef: string, base: string, paths: Array<string>, records: Array<JsValue>, extension?: string | undefined | null): JsWriteOutcome
/**
 * Delete a batch of records by path under `base`, starting from `baseRef`.
 * `existed[i]` reports whether `paths[i]` was actually present.
 */
export declare function recordDelete(gitDir: string, baseRef: string, base: string, paths: Array<string>, extension?: string | undefined | null): JsDeleteOutcome
/**
 * One record from `record_list`: its path (relative to `base`, no extension)
 * and parsed value.
 */
export interface JsRecordEntry {
  path: string
  record: JsValue
}
/**
 * List every record under `base` in the tree `treeRef`, in sorted
 * (git-canonical) path order.
 */
export declare function recordList(gitDir: string, treeRef: string, base: string, extension?: string | undefined | null): Array<JsRecordEntry>
/**
 * Hash raw bytes into the object database as a loose blob, returning its git
 * blob hash — the core's blob-write primitive (replaces the JS package's direct
 * `@hologit/holo-tree` `writeBlob`). Used by the CLI/host to hash a binary
 * attachment before staging it into a record's attachment tree with
 * `CoreTransaction.setAttachment(s)`. The hash is a pure function of the bytes,
 * so Node and Python hashing the same content produce the same object.
 */
export declare function writeBlob(gitDir: string, content: Buffer): string
/**
 * A snapshot of holo-tree's process-wide tree/blob counters — read-side
 * instrumentation for the bulk benchmark and the hologit#464 perf finding.
 */
export interface JsSubstrateStats {
  treesRead: number
  treesWritten: number
  treesSkippedClean: number
  cacheHits: number
  cacheMisses: number
  blobsRead: number
}
/** Snapshot the substrate (holo-tree) counters. */
export declare function substrateStats(): JsSubstrateStats
/** Reset the substrate counters + the thread-local tree cache. */
export declare function substrateReset(): void
/**
 * Query records under `base` in the tree `treeRef`, returning each matched
 * `{ path, record }` in sorted path order. The template prunes the walk; the
 * filter (equality / nested / `$pred` snippets) is applied to each candidate.
 * Batch-first: the whole query crosses the FFI once.
 */
export declare function recordQuery(gitDir: string, treeRef: string, base: string, template: string, filter: object, extension?: string | undefined | null): Array<JsRecordEntry>
/**
 * The pruning candidate set alone (no content filter applied) — the direct
 * parity target for the host `Template.queryTree`. `query` is a (partial)
 * record of the path-template input fields. Returns candidate record paths
 * (relative to `base`, no extension) in sorted order.
 */
export declare function recordQueryCandidates(gitDir: string, treeRef: string, base: string, template: string, query: JsValue, extension?: string | undefined | null): Array<string>
/**
 * The record fields that contribute to rendering `template` — the query
 * auto-derivation set (`Template.getFieldNames` parity). Insertion-ordered,
 * de-duplicated; expression components contribute a best-effort identifier
 * scan minus JS keywords/globals.
 */
export declare function templateFieldNames(template: string): Array<string>
/**
 * Build a **unique** index over the records under `base` and look up each key.
 * `results[i]` is the record for `keys[i]`, or `null` when no record carries
 * it. A duplicate key throws `IndexError(index_unique_conflict)` naming both
 * paths.
 */
export declare function recordIndexUnique(gitDir: string, treeRef: string, base: string, keySnippet: string, keys: Array<string>, extension?: string | undefined | null): Array<JsValue | undefined | null>
/**
 * Build a **non-unique** index over the records under `base` and look up each
 * key. `results[i]` is every record carrying `keys[i]` (an empty array when
 * none).
 */
export declare function recordIndexMulti(gitDir: string, treeRef: string, base: string, keySnippet: string, keys: Array<string>, extension?: string | undefined | null): Array<Array<JsValue>>
/**
 * Generate an RFC 6902 JSON Patch transforming `src` into `dst` — the core's
 * `createPatch`, matching the `rfc6902` package op-for-op. `null`/`undefined`
 * on either side is the JSON null `Sheet.diffFrom` passes for an added
 * (`src=null`) or deleted (`dst=null`) record.
 */
export declare function createPatch(src?: JsValue | undefined | null, dst?: JsValue | undefined | null): object
/**
 * Apply an RFC 7396 JSON Merge Patch to `target` (`null` ⇒ absent), returning
 * the merged record — the core's `mergePatch` behind `Sheet.patch`. A `null`
 * in the patch deletes that key; an object merges recursively; anything else
 * replaces wholesale. Returns `null` only when the patch deletes the record
 * outright.
 */
export declare function applyMergePatch(target: JsValue | undefined | null, patch: JsMergePatch): JsValue | null
/**
 * Diff records between two trees (`srcRef` → `dstRef`) under `base`, returning
 * one entry per change with status, src/dst blob hashes, the parsed src/dst
 * records, and the RFC 6902 patch — the full `Sheet.diffFrom({records,
 * patches})` payload, computed in the core. `srcRef` may be the empty-tree hash
 * for a from-scratch diff.
 */
export declare function diffRecords(gitDir: string, srcRef: string, dstRef: string, base: string, extension?: string | undefined | null): object
/**
 * Throw the core error for a given stable `code`, surfaced as a **structured,
 * matchable** JS error (own `code`, `status`, `gitsheetsClass`, and any
 * `issues`/`conflictingPaths`). Boundary-test entry point: it exercises the
 * error-variant → typed-class mapping without standing up real engine paths.
 */
export declare function simulateCoreError(code: string): void
/** Commit identity for the JS surface. */
export interface JsAuthor {
  name: string
  email: string
}
/** One ordered commit trailer (`Key: value`). */
export interface JsTrailer {
  key: string
  value: string
}
/**
 * Options for opening a [`CoreTransaction`]. `timeSeconds` / `offsetMinutes`
 * carry the host clock + local-timezone offset (a host concern), exactly as the
 * JS `commitTreeWithRepo` computes them today.
 */
export interface JsTransactionOptions {
  parent?: string
  branch?: string
  author?: JsAuthor
  committer?: JsAuthor
  message: string
  trailers?: Array<JsTrailer>
  timeSeconds: number
  offsetMinutes: number
}
/**
 * The outcome of [`CoreTransaction::finalize`]. A no-op (no mutation, or the
 * resulting tree equals the parent's) returns `commitHash = null`.
 */
export interface JsTransactionResult {
  commitHash?: string
  treeHash?: string
  refName?: string
  parentCommitHash?: string
}
/** The outcome of [`CoreTransaction::stage_upsert`]. */
export interface JsStageOutcome {
  blobHash: string
  path: string
}
/**
 * One attachment entry from `CoreTransaction.getAttachments`: its filename and
 * blob hash (name → hash).
 */
export interface JsAttachmentEntry {
  name: string
  hash: string
}
/**
 * Discover every sheet declared in `<openRoot>/.gitsheets/*.toml` in the tree
 * `treeRef`. Sorted bare names. The `Store` discovery half (`openStore`).
 */
export declare function coreDiscoverSheets(gitDir: string, treeRef: string, openRoot: string): Array<string>
/**
 * The `openStore` `config_missing` check: every validator must name a declared
 * sheet. Throws `ConfigError(config_missing)` otherwise.
 */
export declare function coreCheckValidators(declared: Array<string>, validatorNames: Array<string>): void
/**
 * Serialize a record to its on-disk markdown bytes (`+++` frontmatter + body),
 * enforcing the title-from-H1 invariant when `titleField` is set. The body is
 * normalized natively by the embedded `dprint-plugin-markdown` formatter unless
 * `normalize` is `false` (then it is framed verbatim). A non-string body or a
 * title that disagrees with the body's (normalized) H1 throws a typed
 * `ValidationError`.
 */
export declare function markdownSerialize(record: JsValue, bodyField: string, titleField?: string | undefined | null, normalize?: boolean | undefined | null): string
/**
 * Normalize a markdown body with the native `dprint-plugin-markdown` formatter
 * (the pinned aggressive `textWrap: never` config). Deterministic + idempotent.
 * Exposed so the boundary suite can assert the normalizer directly.
 */
export declare function markdownNormalizeBody(body: string): string
/**
 * Parse on-disk markdown bytes into a full record (frontmatter fields + the
 * body under `bodyField`). Mirrors `markdownFormat.parse`.
 */
export declare function markdownParse(text: string, bodyField: string, titleField?: string | undefined | null): JsValue
/**
 * Parse only the frontmatter — the lazy-body path. The body field is absent in
 * the returned record. Mirrors `markdownFormat.parseHeaderOnly`.
 */
export declare function markdownParseHeaderOnly(text: string, bodyField: string): JsValue
/**
 * Extract the first ATX-style H1 from a markdown body, or `null` if absent.
 * Mirrors `extractFirstH1`.
 */
export declare function markdownExtractH1(body: string): string | null
/**
 * Rewrite (or prepend) the first ATX H1 of a markdown body to `title`. Mirrors
 * `rewriteLeadingH1` — the `Sheet.patch` title-reconciliation helper.
 */
export declare function markdownRewriteH1(body: string, title: string): string
/**
 * A compiled sheet definition: the embedded engine plus the definition's
 * path template (and optional raw-JS sort comparator), **compiled once** at
 * construction and reused across every method call. Holds a `!Send` boa
 * context, so it is constructed and used on its owning JS thread — the
 * thread-confinement the spec requires. Exists to demonstrate the
 * compile-once-per-open / reuse-across-operations contract from JS.
 */
export declare class CompiledDefinition {
  /**
   * Compile a definition once: parse the path template (compiling its
   * expression snippets into the engine) and, if given, compile a raw-JS sort
   * comparator. All snippet compilation happens here — never per operation.
   */
  constructor(pathTemplate: string, sortRule?: string | undefined | null)
  /** Render one record's path using the already-compiled template. */
  renderPath(record: JsValue): string
  /**
   * Run the compiled sort comparator on two values, returning its numeric
   * result. Errors if the definition was built without a sort rule.
   */
  compare(a: JsValue, b: JsValue): number
  /**
   * How many snippets were compiled into this definition's engine. Constant
   * across operations — proof that compilation happened once at construction,
   * not per `render_path` / `compare` call.
   */
  snippetCount(): number
}
/**
 * A live transaction the JS boundary suite drives. Holds a `!Send`
 * `Transaction` (repo + private tree) and the opened `Sheet`s, so it is
 * constructed and used on its owning JS thread — the thread-confinement the
 * spec requires.
 */
export declare class CoreTransaction {
  /**
   * Open a transaction against `gitDir`. Resolves the parent/branch, builds
   * the private tree, and acquires the single-writer slot. A concurrent open
   * on the same repo throws `TransactionError(transaction_in_progress)`.
   */
  static begin(gitDir: string, opts: JsTransactionOptions): CoreTransaction
  /**
   * Open a sheet against this transaction's tree (config read + template /
   * schema / sort comparators compiled once).
   */
  openSheet(name: string, configPath: string, openRoot: string, prefix: string): void
  /**
   * Phase 1 of the two-phase protocol *(non-mutating)*. Returns the candidate
   * (`path`, `nextText`, and the normalized `record`) for the host validator;
   * the candidate is stashed for a subsequent `stageUpsert`. A JSON-Schema
   * rejection throws `ValidationError` here, before any bytes are written.
   */
  prepareUpsert(name: string, record: JsValue, previousPath?: string | undefined | null, allowMissingBody?: boolean | undefined | null): object
  /**
   * Phase 3 *(mutating)*: write the stashed candidate from the last
   * `prepareUpsert` for `name`. Marks the transaction mutated.
   */
  stageUpsert(name: string): JsStageOutcome
  /**
   * Pre-flight idempotency check (`Sheet.willChange`) — same phase-1 pipeline,
   * then a byte comparison to the existing blob. Non-mutating.
   */
  willChange(name: string, record: JsValue, previousPath?: string | undefined | null, allowMissingBody?: boolean | undefined | null): object
  /**
   * Delete a record by its sheet-relative path *(mutating)*. Throws
   * `NotFoundError(record_not_found)` when absent.
   */
  delete(name: string, recordPath: string): void
  /** `Sheet.clear` *(mutating)* — empties the sheet's data subtree. */
  clear(name: string): void
  /**
   * Stage attachments for a record *(mutating)*: place each `name → blobHash`
   * at `<recordPath>/<name>` in this transaction's live tree, so the record
   * and its attachments commit atomically. Write the blob first with the
   * top-level `writeBlob`. Marks the transaction mutated.
   */
  setAttachments(name: string, recordPath: string, attachments: Record<string, string>): void
  /** Stage a single attachment *(mutating)* — sugar over [`Self::set_attachments`]. */
  setAttachment(name: string, recordPath: string, attachmentName: string, blobHash: string): void
  /**
   * The blob-hash map of a record's attachments (`name → hash`, sorted by
   * name), or `null` when the record has no attachment directory. Read-only.
   */
  getAttachments(name: string, recordPath: string): Array<JsAttachmentEntry> | null
  /** The blob hash of a single named attachment, or `null` if absent. Read-only. */
  getAttachment(name: string, recordPath: string, attachmentName: string): string | null
  /**
   * Remove a single named attachment *(mutating)*. Throws
   * `NotFoundError(record_not_found)` when it doesn't exist. Marks mutated.
   */
  deleteAttachment(name: string, recordPath: string, attachmentName: string): void
  /**
   * Remove all attachments for a record *(mutating)*. A no-op when the record
   * has no attachment directory — in that case the transaction is NOT marked
   * mutated (so an otherwise-empty transaction still finalizes to no commit).
   * Returns whether anything was removed.
   */
  deleteAttachments(name: string, recordPath: string): boolean
  /**
   * List every record under the sheet's base, decoded through the format
   * codec, in sorted path order. `withBody` is the lazy-body switch for
   * markdown sheets (`false` omits the body field); a no-op for TOML sheets.
   * Read-only — does not mark the transaction mutated.
   */
  list(name: string, withBody: boolean): Array<JsRecordEntry>
  /** The parent commit hash captured at open (null on a fresh repo). */
  parentCommitHash(): string | null
  /**
   * Finalize: commit-on-success-only with no-op detection + `parent_moved`
   * re-check + CAS ref movement. Consumes the transaction.
   */
  finalize(): JsTransactionResult
  /** Discard without committing (handler threw). Releases the writer slot. */
  discard(): void
}
